# Generated by Django 4.0.2 on 2022-02-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
