# Generated by Django 3.2.8 on 2021-11-18 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50)]),
        )
    ]
