# Generated by Django 3.2.9 on 2021-11-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0002_alter_product_price")]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(blank=True, null=True, upload_to="products/")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ecommerce.product")),
            ],
        )
    ]
