# Generated by Django 4.0.3 on 2022-05-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0002_initial")]

    operations = [
        migrations.AlterField(model_name="category", name="slug", field=models.SlugField(max_length=100, unique=True)),
        migrations.AlterField(
            model_name="category", name="title", field=models.CharField(max_length=100, unique=True)
        ),
        migrations.AlterField(
            model_name="product", name="slug", field=models.SlugField(blank=True, null=True, unique=True)
        ),
    ]
