# Generated by Django 4.0.2 on 2022-02-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
