# Generated by Django 4.0.2 on 2022-03-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
