# Generated by Django 4.0.3 on 2022-06-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0005_alter_category_slug_alter_product_category")]

    operations = [
        migrations.AlterField(model_name="product", name="title", field=models.CharField(max_length=250, unique=True))
    ]
