# Generated by Django 4.0.6 on 2022-09-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0006_alter_product_title")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_location",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        )
    ]
