# Generated by Django 4.0.1 on 2022-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_image_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_location',
            field=models.ImageField(blank=True, null=True, upload_to='media/products'),
        ),
    ]
