name: Django tests

on:
  push:
    branches: [ main, redis_and_model_registered]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pipenv
      run: |
        python -m pip install pipenv
    - name: Create virtual environment with dependencies
      run: |
        python -m pipenv install
    - name: Run Tests
      run: |
        pipenv run python manage.py test
