name: Django tests

on:
  push:
    branches: [ main, redis_and_model_registered]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      run: |
        python -m pip install pipenv
    - name: Create virtual environment with dependencies
      run: |
        python -m pipenv install
    - name: Activate virtual environment
      run: |
        python -m pipenv shell
    - name: Run Tests
      run: |
        python manage.py test
